version: '0.1'
services:
  xxl-job:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: xxl-job
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://192.168.225.128:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai  --spring.datasource.username=root  --spring.datasource.password=root --spring.config.loation=/application.properties"
    ports:
      - 8088:8080
    volumes:
      - ./logs/:/data/applogs/xxl-job/
      - ./application.properties:/application.properties 
      - ./applogs:/data/applogs  